# Generated by Django 5.0.2 on 2024-03-02 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequirementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('enabled', models.BooleanField()),
                ('answer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotQuestions.answertype')),
                ('requirement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotQuestions.requirementtype')),
            ],
        ),
    ]
